// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI Pricing Assistant Flow.
 *
 * This file defines a Genkit flow for suggesting a reasonable price for a 3D printed item
 * based on its description, material, and printing time.
 *
 * @exports suggestPricing - The main function to trigger the pricing suggestion flow.
 * @exports SuggestPricingInput - The input type for the suggestPricing function.
 * @exports SuggestPricingOutput - The output type for the suggestPricing function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestPricingInputSchema = z.object({
  productDescription: z.string().describe('A detailed description of the 3D printed product.'),
  materialUsed: z.string().describe('The type of material used for printing (e.g., PLA, ABS, PETG).'),
  printingTime: z.string().describe('The total printing time in hours.'),
});

export type SuggestPricingInput = z.infer<typeof SuggestPricingInputSchema>;

const SuggestPricingOutputSchema = z.object({
  suggestedPrice: z.string().describe('A suggested selling price for the 3D printed item.'),
  reasoning: z.string().describe('The AI reasoning behind the suggested price.'),
});

export type SuggestPricingOutput = z.infer<typeof SuggestPricingOutputSchema>;

export async function suggestPricing(input: SuggestPricingInput): Promise<SuggestPricingOutput> {
  return suggestPricingFlow(input);
}

const suggestPricingPrompt = ai.definePrompt({
  name: 'suggestPricingPrompt',
  input: {schema: SuggestPricingInputSchema},
  output: {schema: SuggestPricingOutputSchema},
  prompt: `You are an AI pricing assistant for 3D printed products.
  Based on the product description, material used, and printing time, suggest a reasonable selling price.
  Provide a brief explanation of your reasoning behind the suggested price.

  Product Description: {{{productDescription}}}
  Material Used: {{{materialUsed}}}
  Printing Time: {{{printingTime}}}`,
});

const suggestPricingFlow = ai.defineFlow(
  {
    name: 'suggestPricingFlow',
    inputSchema: SuggestPricingInputSchema,
    outputSchema: SuggestPricingOutputSchema,
  },
  async input => {
    const {output} = await suggestPricingPrompt(input);
    return output!;
  }
);
